#ifndef __wxPriceQueryForOriginLoadingDialog__
#define __wxPriceQueryForOriginLoadingDialog__

/**
@file
Subclass of LoadingDialog, which is generated by wxFormBuilder.
*/

#include "frame.h"

//// end generated include

/** Implementing LoadingDialog */
class wxPriceQueryForOriginLoadingDialog : public LoadingDialog
{
	public:
		/** Constructor */
		wxPriceQueryForOriginLoadingDialog( wxWindow* parent );
	//// end generated class members

		void SetDisplayText(wxString text);
};

#endif // __wxPriceQueryForOriginLoadingDialog__
