#ifndef __wxPriceQueryForOriginAboutDialog__
#define __wxPriceQueryForOriginAboutDialog__

/**
@file
Subclass of AboutDialog, which is generated by wxFormBuilder.
*/

#include "frame.h"

//// end generated include

#include "../languages/languages.hpp"

/** Implementing AboutDialog */
class wxPriceQueryForOriginAboutDialog : public AboutDialog
{
	public:
		/** Constructor */
		wxPriceQueryForOriginAboutDialog( wxWindow* parent );
	//// end generated class members

private:
	languages::Language current_language;

public:
	void SetLanguage(languages::Language lng);
};

#endif // __wxPriceQueryForOriginAboutDialog__
