#ifndef __wxPriceQueryForOriginSettingDialog__
#define __wxPriceQueryForOriginSettingDialog__

/**
@file
Subclass of SettingDialog, which is generated by wxFormBuilder.
*/

#include "frame.h"

//// end generated include

#include <memory>
#include <string>
#include <vector>
#include <wx/msgdlg.h>
#include "../query_tools/origin_tools/OriginQueries.hpp"
#include "../query_tools/exchange_rate/CurrencyAPI.hpp"
#include "../languages/languages.hpp"

/** Implementing SettingDialog */
class wxPriceQueryForOriginSettingDialog : public SettingDialog
{
	protected:
		// Handlers for SettingDialog events.
		void OnChoiceInterfaceLanguage( wxCommandEvent& event );
		void OnClockCancel( wxCommandEvent& event );
		void OnClickOK( wxCommandEvent& event );
	public:
		/** Constructor */
		wxPriceQueryForOriginSettingDialog( wxWindow* parent );
	//// end generated class members

private:
	languages::Language current_language;
	//std::string current_currency;
	//std::string current_origin_language;
	//std::string current_region;
	std::vector<languages::Language> interface_selection_list;
	std::vector<wxString> currency_selection_list;
	std::vector<wxString> game_language_selection_list;
	std::vector<wxString> country_selection_list;
	std::shared_ptr<query_tools::OriginQueries> queries_ptr;
	std::shared_ptr<currency_tools::CurrencyAPI> currency_api_ptr;

	void InitialiseApplication();

public:
	void SetQueryClass(std::shared_ptr<query_tools::OriginQueries> input_ptr) { queries_ptr = input_ptr; }
	void SetQueryClass(std::shared_ptr<currency_tools::CurrencyAPI> input_ptr) { currency_api_ptr = input_ptr; }
	void SetQueryClass(std::nullptr_t input_ptr) { queries_ptr = nullptr; currency_api_ptr = nullptr; }
	bool InitialiseConnections(std::function<void(std::string newmsg)> update_progress);
	void GetClientSettings(languages::Language &interface_lng, wxString &selected_currency, wxString &origin_lng, wxString &origin_country);
};

#endif // __wxPriceQueryForOriginSettingDialog__
